server:
  port: 8083

spring:
  application:
    name: recommendation-service
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: recommendation-group

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/